spring.application.name=apothocary-service

spring.h2.console.enabled=true
# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/apothecary_db
spring.datasource.username=apothecary_user
spring.datasource.password=apothecary_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Show all queries
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop

logging.level.org.hibernate.type=trace
logging.level.org.hibernate.boot=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG
